cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
      static: eu-north-1
    stack:
      auto: false

application:
  bucket:
    name: ${AWS_BUCKET_NAME}


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 10MB
      max-request-size: 10MB

twilio:
  account_sid: ${TWILIO_SID}
  token: ${TWILIO_TOKEN}
  from_number: ${TWILIO_NUMBER}